Update gedcom.ts
Delete ENGA event. With this event Travis say error:

src/gedcom.ts:288:9 - error TS2339: Property 'engagement' does not exist on type 'JsonFam'.
288     fam.engagement = engagement;
            ~~~~~~~~~~
Found 1 error.